// 어워드 저널 엔트리 목록 — 새 리뷰마다 맨 앞에 한 객체 추가
const ENTRIES = [
  {
    folder: "2026-09-28-meech213",
    name: "Meech213",
    url: "https://www.meech213.com/",
    date: "2026-09-28",
    thumb: "02-rotated.png",
    comment: "이미지·영상이 원통에 감겨 입체감 있게 롤링. 가운데가 작고 양옆이 크게 감싸는 오목 시점",
    style: ["미니멀", "크림톤", "패션", "매거진"],
    industry: ["포트폴리오", "포토그래퍼"],
    interaction: ["롤링갤러리", "원통캐러셀", "WebGL이미지", "비디오텍스처", "다이얼내비"],
  },
  {
    folder: "2026-09-28-bleibtgleich",
    name: "Maksym Bleibtgleich",
    url: "https://bleibtgleich.dev/",
    date: "2026-09-28",
    thumb: "02-goo-mid.png",
    comment: "스크롤을 내리면 폰트가 잉크처럼 녹아 있다가 굳으며 나타나는 플루이드 효과",
    style: ["미니멀", "타이포중심", "화이트", "스위스그리드"],
    industry: ["포트폴리오", "디자이너개인"],
    interaction: ["플루이드텍스트", "구이필터", "스크롤리빌", "스무스스크롤"],
  },
  {
    folder: "2026-09-21-gilhuybrecht",
    name: "Gil Huybrecht",
    url: "https://gilhuybrecht.com/",
    date: "2026-09-21",
    thumb: "01-grid-home.png",
    comment: "미니멀+높은 X하이트 폰트. 리스트↔상세 전환 모션이 평면적인 디자인을 입체감 있게 바꿔준다",
    style: ["미니멀", "타이포중심", "화이트", "에디토리얼"],
    industry: ["포트폴리오", "디자이너개인"],
    interaction: ["뷰트랜지션", "FLIP", "썸네일확대", "WebGL이미지", "스무스스크롤", "그리드갤러리전환"],
  },
];
